# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.user_schedulers_list_schedulers import UserSchedulersListSchedulers  # noqa: E501
from swagger_client.rest import ApiException


class TestUserSchedulersListSchedulers(unittest.TestCase):
    """UserSchedulersListSchedulers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserSchedulersListSchedulers(self):
        """Test UserSchedulersListSchedulers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_schedulers_list_schedulers.UserSchedulersListSchedulers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
