# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.dashboards_api import DashboardsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDashboardsApi(unittest.TestCase):
    """DashboardsApi unit test stubs"""

    def setUp(self):
        self.api = api.dashboards_api.DashboardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dashboard_client_feedback(self):
        """Test case for dashboard_client_feedback

        List Zoom Meetings Client Feedbacks  # noqa: E501
        """
        pass

    def test_dashboard_client_feedback_detail(self):
        """Test case for dashboard_client_feedback_detail

        Get Zoom Meetings Client Feedback  # noqa: E501
        """
        pass

    def test_dashboard_crc(self):
        """Test case for dashboard_crc

        Get CRC Port Usage  # noqa: E501
        """
        pass

    def test_dashboard_im(self):
        """Test case for dashboard_im

        Get IM Metrics  # noqa: E501
        """
        pass

    def test_dashboard_issue_detail_zoom_room(self):
        """Test case for dashboard_issue_detail_zoom_room

        Get Issues of Zoom Rooms   # noqa: E501
        """
        pass

    def test_dashboard_issue_zoom_room(self):
        """Test case for dashboard_issue_zoom_room

        Get Top 25 Zoom Rooms with Issues  # noqa: E501
        """
        pass

    def test_dashboard_meeting_detail(self):
        """Test case for dashboard_meeting_detail

        Get Meeting Details  # noqa: E501
        """
        pass

    def test_dashboard_meeting_participant_qos(self):
        """Test case for dashboard_meeting_participant_qos

        Get Meeting Participant QOS  # noqa: E501
        """
        pass

    def test_dashboard_meeting_participant_share(self):
        """Test case for dashboard_meeting_participant_share

        Get Sharing/Recording Details of Meeting Participants  # noqa: E501
        """
        pass

    def test_dashboard_meeting_participants(self):
        """Test case for dashboard_meeting_participants

        List Meeting Participants  # noqa: E501
        """
        pass

    def test_dashboard_meeting_participants_qos(self):
        """Test case for dashboard_meeting_participants_qos

        List Meeting Participants QOS  # noqa: E501
        """
        pass

    def test_dashboard_meetings(self):
        """Test case for dashboard_meetings

        List Meetings  # noqa: E501
        """
        pass

    def test_dashboard_webinar_detail(self):
        """Test case for dashboard_webinar_detail

        Get Webinar Details  # noqa: E501
        """
        pass

    def test_dashboard_webinar_participant_qos(self):
        """Test case for dashboard_webinar_participant_qos

        Get Webinar Participant QOS  # noqa: E501
        """
        pass

    def test_dashboard_webinar_participant_share(self):
        """Test case for dashboard_webinar_participant_share

        Get Sharing/Recording Details of Webinar Participants  # noqa: E501
        """
        pass

    def test_dashboard_webinar_participants(self):
        """Test case for dashboard_webinar_participants

        Get Webinar Participants  # noqa: E501
        """
        pass

    def test_dashboard_webinar_participants_qos(self):
        """Test case for dashboard_webinar_participants_qos

        List Webinar Participant QOS  # noqa: E501
        """
        pass

    def test_dashboard_webinars(self):
        """Test case for dashboard_webinars

        List Webinars  # noqa: E501
        """
        pass

    def test_dashboard_zoom_room(self):
        """Test case for dashboard_zoom_room

        Get Zoom Rooms Details  # noqa: E501
        """
        pass

    def test_dashboard_zoom_room_issue(self):
        """Test case for dashboard_zoom_room_issue

        Get Top 25 issues of Zoom Rooms  # noqa: E501
        """
        pass

    def test_dashboard_zoom_rooms(self):
        """Test case for dashboard_zoom_rooms

        List Zoom Rooms  # noqa: E501
        """
        pass

    def test_list_meeting_satisfaction(self):
        """Test case for list_meeting_satisfaction

        List Client Meeting Satisfaction   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
