# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.groups_api import GroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_group_lock_settings(self):
        """Test case for get_group_lock_settings

        Get Locked Settings  # noqa: E501
        """
        pass

    def test_get_group_settings(self):
        """Test case for get_group_settings

        Get a Group's Settings  # noqa: E501
        """
        pass

    def test_group(self):
        """Test case for group

        Get a Group  # noqa: E501
        """
        pass

    def test_group_create(self):
        """Test case for group_create

        Create a Group  # noqa: E501
        """
        pass

    def test_group_delete(self):
        """Test case for group_delete

        Delete a Group  # noqa: E501
        """
        pass

    def test_group_locked_settings(self):
        """Test case for group_locked_settings

        Update Locked Settings  # noqa: E501
        """
        pass

    def test_group_members(self):
        """Test case for group_members

        List Group Members   # noqa: E501
        """
        pass

    def test_group_members_create(self):
        """Test case for group_members_create

        Add Group Members  # noqa: E501
        """
        pass

    def test_group_members_delete(self):
        """Test case for group_members_delete

        Delete a Group Member  # noqa: E501
        """
        pass

    def test_group_update(self):
        """Test case for group_update

        Update a Group  # noqa: E501
        """
        pass

    def test_groups(self):
        """Test case for groups

        List Groups  # noqa: E501
        """
        pass

    def test_update_a_group_member(self):
        """Test case for update_a_group_member

        Update a Group Member  # noqa: E501
        """
        pass

    def test_update_group_settings(self):
        """Test case for update_group_settings

        Update a Group's Settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
