# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class IMGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'search_by_domain': 'bool',
        'search_by_account': 'bool',
        'search_by_ma_account': 'bool'
    }

    attribute_map = {
        'type': 'type',
        'search_by_domain': 'search_by_domain',
        'search_by_account': 'search_by_account',
        'search_by_ma_account': 'search_by_ma_account'
    }

    def __init__(self, type='normal', search_by_domain=None, search_by_account=None, search_by_ma_account=None):  # noqa: E501
        """IMGroup - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._search_by_domain = None
        self._search_by_account = None
        self._search_by_ma_account = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if search_by_domain is not None:
            self.search_by_domain = search_by_domain
        if search_by_account is not None:
            self.search_by_account = search_by_account
        if search_by_ma_account is not None:
            self.search_by_ma_account = search_by_ma_account

    @property
    def type(self):
        """Gets the type of this IMGroup.  # noqa: E501

        IM Group types:<br>`normal` - Only members can see the other members in the group. Other people can search for members in the group.<br>`shared` - Everyone in the account can see the group and members. <br>`restricted` - No one except group members can see the group or search for other group members.   # noqa: E501

        :return: The type of this IMGroup.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this IMGroup.

        IM Group types:<br>`normal` - Only members can see the other members in the group. Other people can search for members in the group.<br>`shared` - Everyone in the account can see the group and members. <br>`restricted` - No one except group members can see the group or search for other group members.   # noqa: E501

        :param type: The type of this IMGroup.  # noqa: E501
        :type: str
        """
        allowed_values = ["normal", "shared", "restricted"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def search_by_domain(self):
        """Gets the search_by_domain of this IMGroup.  # noqa: E501

        Members can search for others in the same email domain.  # noqa: E501

        :return: The search_by_domain of this IMGroup.  # noqa: E501
        :rtype: bool
        """
        return self._search_by_domain

    @search_by_domain.setter
    def search_by_domain(self, search_by_domain):
        """Sets the search_by_domain of this IMGroup.

        Members can search for others in the same email domain.  # noqa: E501

        :param search_by_domain: The search_by_domain of this IMGroup.  # noqa: E501
        :type: bool
        """

        self._search_by_domain = search_by_domain

    @property
    def search_by_account(self):
        """Gets the search_by_account of this IMGroup.  # noqa: E501

        Members can search for others under same account.  # noqa: E501

        :return: The search_by_account of this IMGroup.  # noqa: E501
        :rtype: bool
        """
        return self._search_by_account

    @search_by_account.setter
    def search_by_account(self, search_by_account):
        """Sets the search_by_account of this IMGroup.

        Members can search for others under same account.  # noqa: E501

        :param search_by_account: The search_by_account of this IMGroup.  # noqa: E501
        :type: bool
        """

        self._search_by_account = search_by_account

    @property
    def search_by_ma_account(self):
        """Gets the search_by_ma_account of this IMGroup.  # noqa: E501

        Members can search for others under same master account - including all sub accounts.  # noqa: E501

        :return: The search_by_ma_account of this IMGroup.  # noqa: E501
        :rtype: bool
        """
        return self._search_by_ma_account

    @search_by_ma_account.setter
    def search_by_ma_account(self, search_by_ma_account):
        """Sets the search_by_ma_account of this IMGroup.

        Members can search for others under same master account - including all sub accounts.  # noqa: E501

        :param search_by_ma_account: The search_by_ma_account of this IMGroup.  # noqa: E501
        :type: bool
        """

        self._search_by_ma_account = search_by_ma_account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IMGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IMGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
