# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse2014(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'added_at': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'added_at': 'added_at'
    }

    def __init__(self, id=None, added_at=None):  # noqa: E501
        """InlineResponse2014 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._added_at = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if added_at is not None:
            self.added_at = added_at

    @property
    def id(self):
        """Gets the id of this InlineResponse2014.  # noqa: E501

        Member Id of the user who joined the public channel.  # noqa: E501

        :return: The id of this InlineResponse2014.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2014.

        Member Id of the user who joined the public channel.  # noqa: E501

        :param id: The id of this InlineResponse2014.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def added_at(self):
        """Gets the added_at of this InlineResponse2014.  # noqa: E501

        The date and time at which a user joined the channel.  # noqa: E501

        :return: The added_at of this InlineResponse2014.  # noqa: E501
        :rtype: datetime
        """
        return self._added_at

    @added_at.setter
    def added_at(self, added_at):
        """Sets the added_at of this InlineResponse2014.

        The date and time at which a user joined the channel.  # noqa: E501

        :param added_at: The added_at of this InlineResponse2014.  # noqa: E501
        :type: datetime
        """

        self._added_at = added_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2014, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2014):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
