# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20093CallingPlans(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'int',
        'subscribed': 'int',
        'assigned': 'int',
        'available': 'int'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'subscribed': 'subscribed',
        'assigned': 'assigned',
        'available': 'available'
    }

    def __init__(self, name=None, type=None, subscribed=None, assigned=None, available=None):  # noqa: E501
        """InlineResponse20093CallingPlans - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._type = None
        self._subscribed = None
        self._assigned = None
        self._available = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if subscribed is not None:
            self.subscribed = subscribed
        if assigned is not None:
            self.assigned = assigned
        if available is not None:
            self.available = available

    @property
    def name(self):
        """Gets the name of this InlineResponse20093CallingPlans.  # noqa: E501

        Name of the plan.  # noqa: E501

        :return: The name of this InlineResponse20093CallingPlans.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20093CallingPlans.

        Name of the plan.  # noqa: E501

        :param name: The name of this InlineResponse20093CallingPlans.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this InlineResponse20093CallingPlans.  # noqa: E501

        Plan type. Refer to the Plan Number section [here](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans).  # noqa: E501

        :return: The type of this InlineResponse20093CallingPlans.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse20093CallingPlans.

        Plan type. Refer to the Plan Number section [here](https://marketplace.zoom.us/docs/api-reference/other-references/plans#zoom-phone-calling-plans).  # noqa: E501

        :param type: The type of this InlineResponse20093CallingPlans.  # noqa: E501
        :type: int
        """

        self._type = type

    @property
    def subscribed(self):
        """Gets the subscribed of this InlineResponse20093CallingPlans.  # noqa: E501

        Total number of plan subscriptions bought.  # noqa: E501

        :return: The subscribed of this InlineResponse20093CallingPlans.  # noqa: E501
        :rtype: int
        """
        return self._subscribed

    @subscribed.setter
    def subscribed(self, subscribed):
        """Sets the subscribed of this InlineResponse20093CallingPlans.

        Total number of plan subscriptions bought.  # noqa: E501

        :param subscribed: The subscribed of this InlineResponse20093CallingPlans.  # noqa: E501
        :type: int
        """

        self._subscribed = subscribed

    @property
    def assigned(self):
        """Gets the assigned of this InlineResponse20093CallingPlans.  # noqa: E501

        Total number of plan used.  # noqa: E501

        :return: The assigned of this InlineResponse20093CallingPlans.  # noqa: E501
        :rtype: int
        """
        return self._assigned

    @assigned.setter
    def assigned(self, assigned):
        """Sets the assigned of this InlineResponse20093CallingPlans.

        Total number of plan used.  # noqa: E501

        :param assigned: The assigned of this InlineResponse20093CallingPlans.  # noqa: E501
        :type: int
        """

        self._assigned = assigned

    @property
    def available(self):
        """Gets the available of this InlineResponse20093CallingPlans.  # noqa: E501

        Remaining number of calling plans that can be assigned.  # noqa: E501

        :return: The available of this InlineResponse20093CallingPlans.  # noqa: E501
        :rtype: int
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this InlineResponse20093CallingPlans.

        Remaining number of calling plans that can be assigned.  # noqa: E501

        :param available: The available of this InlineResponse20093CallingPlans.  # noqa: E501
        :type: int
        """

        self._available = available

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20093CallingPlans, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20093CallingPlans):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
