# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20094Users(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'phone_user_id': 'str',
        'name': 'str',
        'email': 'str',
        'site': 'InlineResponse20094Site',
        'extension_number': 'int',
        'status': 'str',
        'calling_plans': 'list[InlineResponse20094CallingPlans]'
    }

    attribute_map = {
        'id': 'id',
        'phone_user_id': 'phone_user_id',
        'name': 'name',
        'email': 'email',
        'site': 'site',
        'extension_number': 'extension_number',
        'status': 'status',
        'calling_plans': 'calling_plans'
    }

    def __init__(self, id=None, phone_user_id=None, name=None, email=None, site=None, extension_number=None, status=None, calling_plans=None):  # noqa: E501
        """InlineResponse20094Users - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._phone_user_id = None
        self._name = None
        self._email = None
        self._site = None
        self._extension_number = None
        self._status = None
        self._calling_plans = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if phone_user_id is not None:
            self.phone_user_id = phone_user_id
        if name is not None:
            self.name = name
        if email is not None:
            self.email = email
        if site is not None:
            self.site = site
        if extension_number is not None:
            self.extension_number = extension_number
        if status is not None:
            self.status = status
        if calling_plans is not None:
            self.calling_plans = calling_plans

    @property
    def id(self):
        """Gets the id of this InlineResponse20094Users.  # noqa: E501

        Unique Identifier of the user (userId).  # noqa: E501

        :return: The id of this InlineResponse20094Users.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20094Users.

        Unique Identifier of the user (userId).  # noqa: E501

        :param id: The id of this InlineResponse20094Users.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def phone_user_id(self):
        """Gets the phone_user_id of this InlineResponse20094Users.  # noqa: E501

        Zoom Phone Identifier of the user.  # noqa: E501

        :return: The phone_user_id of this InlineResponse20094Users.  # noqa: E501
        :rtype: str
        """
        return self._phone_user_id

    @phone_user_id.setter
    def phone_user_id(self, phone_user_id):
        """Sets the phone_user_id of this InlineResponse20094Users.

        Zoom Phone Identifier of the user.  # noqa: E501

        :param phone_user_id: The phone_user_id of this InlineResponse20094Users.  # noqa: E501
        :type: str
        """

        self._phone_user_id = phone_user_id

    @property
    def name(self):
        """Gets the name of this InlineResponse20094Users.  # noqa: E501

        Name of the user.  # noqa: E501

        :return: The name of this InlineResponse20094Users.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20094Users.

        Name of the user.  # noqa: E501

        :param name: The name of this InlineResponse20094Users.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def email(self):
        """Gets the email of this InlineResponse20094Users.  # noqa: E501

        Email address of the user.  # noqa: E501

        :return: The email of this InlineResponse20094Users.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this InlineResponse20094Users.

        Email address of the user.  # noqa: E501

        :param email: The email of this InlineResponse20094Users.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def site(self):
        """Gets the site of this InlineResponse20094Users.  # noqa: E501


        :return: The site of this InlineResponse20094Users.  # noqa: E501
        :rtype: InlineResponse20094Site
        """
        return self._site

    @site.setter
    def site(self, site):
        """Sets the site of this InlineResponse20094Users.


        :param site: The site of this InlineResponse20094Users.  # noqa: E501
        :type: InlineResponse20094Site
        """

        self._site = site

    @property
    def extension_number(self):
        """Gets the extension_number of this InlineResponse20094Users.  # noqa: E501

        Extension number assigned to the user's Zoom phone number.  # noqa: E501

        :return: The extension_number of this InlineResponse20094Users.  # noqa: E501
        :rtype: int
        """
        return self._extension_number

    @extension_number.setter
    def extension_number(self, extension_number):
        """Sets the extension_number of this InlineResponse20094Users.

        Extension number assigned to the user's Zoom phone number.  # noqa: E501

        :param extension_number: The extension_number of this InlineResponse20094Users.  # noqa: E501
        :type: int
        """

        self._extension_number = extension_number

    @property
    def status(self):
        """Gets the status of this InlineResponse20094Users.  # noqa: E501

        Displays the status of the user's Zoom Phone license. The value can be either of the following:<br> `activate`: Active Zoom phone user.<br> `deactivate`: User with Zoom phone license disabled. This type of user can't make or receive calls.  # noqa: E501

        :return: The status of this InlineResponse20094Users.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20094Users.

        Displays the status of the user's Zoom Phone license. The value can be either of the following:<br> `activate`: Active Zoom phone user.<br> `deactivate`: User with Zoom phone license disabled. This type of user can't make or receive calls.  # noqa: E501

        :param status: The status of this InlineResponse20094Users.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def calling_plans(self):
        """Gets the calling_plans of this InlineResponse20094Users.  # noqa: E501


        :return: The calling_plans of this InlineResponse20094Users.  # noqa: E501
        :rtype: list[InlineResponse20094CallingPlans]
        """
        return self._calling_plans

    @calling_plans.setter
    def calling_plans(self, calling_plans):
        """Sets the calling_plans of this InlineResponse20094Users.


        :param calling_plans: The calling_plans of this InlineResponse20094Users.  # noqa: E501
        :type: list[InlineResponse20094CallingPlans]
        """

        self._calling_plans = calling_plans

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20094Users, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20094Users):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
