# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse201(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'location_id': 'str',
        'room_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'location_id': 'location_id',
        'room_id': 'room_id'
    }

    def __init__(self, id=None, name=None, type=None, location_id=None, room_id=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._type = None
        self._location_id = None
        self._room_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if location_id is not None:
            self.location_id = location_id
        if room_id is not None:
            self.room_id = room_id

    @property
    def id(self):
        """Gets the id of this InlineResponse201.  # noqa: E501

        Unique Identifier of the Zoom Room.  # noqa: E501

        :return: The id of this InlineResponse201.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse201.

        Unique Identifier of the Zoom Room.  # noqa: E501

        :param id: The id of this InlineResponse201.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this InlineResponse201.  # noqa: E501

        Name of the Zoom Room.  # noqa: E501

        :return: The name of this InlineResponse201.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse201.

        Name of the Zoom Room.  # noqa: E501

        :param name: The name of this InlineResponse201.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this InlineResponse201.  # noqa: E501

        Type of the Zoom Room.  # noqa: E501

        :return: The type of this InlineResponse201.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse201.

        Type of the Zoom Room.  # noqa: E501

        :param type: The type of this InlineResponse201.  # noqa: E501
        :type: str
        """
        allowed_values = ["ZoomRoom", "SchedulingDisplayOnly", "DigitalSignageOnly"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def location_id(self):
        """Gets the location_id of this InlineResponse201.  # noqa: E501

        Location ID of the location where the Zoom Room was added.  # noqa: E501

        :return: The location_id of this InlineResponse201.  # noqa: E501
        :rtype: str
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """Sets the location_id of this InlineResponse201.

        Location ID of the location where the Zoom Room was added.  # noqa: E501

        :param location_id: The location_id of this InlineResponse201.  # noqa: E501
        :type: str
        """

        self._location_id = location_id

    @property
    def room_id(self):
        """Gets the room_id of this InlineResponse201.  # noqa: E501

        Globally unique identifier of the Zoom Room. Use this ID for the **Dashboard Zoom Room APIs**.  # noqa: E501

        :return: The room_id of this InlineResponse201.  # noqa: E501
        :rtype: str
        """
        return self._room_id

    @room_id.setter
    def room_id(self, room_id):
        """Sets the room_id of this InlineResponse201.

        Globally unique identifier of the Zoom Room. Use this ID for the **Dashboard Zoom Room APIs**.  # noqa: E501

        :param room_id: The room_id of this InlineResponse201.  # noqa: E501
        :type: str
        """

        self._room_id = room_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse201, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse201):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
