# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Occurrence(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'occurrence_id': 'str',
        'start_time': 'datetime',
        'duration': 'int',
        'status': 'str'
    }

    attribute_map = {
        'occurrence_id': 'occurrence_id',
        'start_time': 'start_time',
        'duration': 'duration',
        'status': 'status'
    }

    def __init__(self, occurrence_id=None, start_time=None, duration=None, status=None):  # noqa: E501
        """Occurrence - a model defined in Swagger"""  # noqa: E501
        self._occurrence_id = None
        self._start_time = None
        self._duration = None
        self._status = None
        self.discriminator = None
        if occurrence_id is not None:
            self.occurrence_id = occurrence_id
        if start_time is not None:
            self.start_time = start_time
        if duration is not None:
            self.duration = duration
        if status is not None:
            self.status = status

    @property
    def occurrence_id(self):
        """Gets the occurrence_id of this Occurrence.  # noqa: E501

        Occurrence ID: Unique Identifier that identifies an occurrence of a recurring webinar. [Recurring webinars](https://support.zoom.us/hc/en-us/articles/216354763-How-to-Schedule-A-Recurring-Webinar) can have a maximum of 50 occurrences.  # noqa: E501

        :return: The occurrence_id of this Occurrence.  # noqa: E501
        :rtype: str
        """
        return self._occurrence_id

    @occurrence_id.setter
    def occurrence_id(self, occurrence_id):
        """Sets the occurrence_id of this Occurrence.

        Occurrence ID: Unique Identifier that identifies an occurrence of a recurring webinar. [Recurring webinars](https://support.zoom.us/hc/en-us/articles/216354763-How-to-Schedule-A-Recurring-Webinar) can have a maximum of 50 occurrences.  # noqa: E501

        :param occurrence_id: The occurrence_id of this Occurrence.  # noqa: E501
        :type: str
        """

        self._occurrence_id = occurrence_id

    @property
    def start_time(self):
        """Gets the start_time of this Occurrence.  # noqa: E501

        Start time.  # noqa: E501

        :return: The start_time of this Occurrence.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this Occurrence.

        Start time.  # noqa: E501

        :param start_time: The start_time of this Occurrence.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def duration(self):
        """Gets the duration of this Occurrence.  # noqa: E501

        Duration.  # noqa: E501

        :return: The duration of this Occurrence.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this Occurrence.

        Duration.  # noqa: E501

        :param duration: The duration of this Occurrence.  # noqa: E501
        :type: int
        """

        self._duration = duration

    @property
    def status(self):
        """Gets the status of this Occurrence.  # noqa: E501

        Occurrence status.  # noqa: E501

        :return: The status of this Occurrence.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Occurrence.

        Occurrence status.  # noqa: E501

        :param status: The status of this Occurrence.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Occurrence, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Occurrence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
