# coding: utf-8

"""
    Zoom API

    The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: developersupport@zoom.us
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ZoomRoom(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'room_name': 'str',
        'calender_name': 'str',
        'email': 'str',
        'account_type': 'str',
        'status': 'str',
        'device_ip': 'str',
        'camera': 'str',
        'microphone': 'str',
        'speaker': 'str',
        'last_start_time': 'str',
        'location': 'str',
        'health': 'str',
        'issues': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'room_name': 'room_name',
        'calender_name': 'calender_name',
        'email': 'email',
        'account_type': 'account_type',
        'status': 'status',
        'device_ip': 'device_ip',
        'camera': 'camera',
        'microphone': 'microphone',
        'speaker': 'speaker',
        'last_start_time': 'last_start_time',
        'location': 'location',
        'health': 'health',
        'issues': 'issues'
    }

    def __init__(self, id=None, room_name=None, calender_name=None, email=None, account_type=None, status=None, device_ip=None, camera=None, microphone=None, speaker=None, last_start_time=None, location=None, health=None, issues=None):  # noqa: E501
        """ZoomRoom - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._room_name = None
        self._calender_name = None
        self._email = None
        self._account_type = None
        self._status = None
        self._device_ip = None
        self._camera = None
        self._microphone = None
        self._speaker = None
        self._last_start_time = None
        self._location = None
        self._health = None
        self._issues = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if room_name is not None:
            self.room_name = room_name
        if calender_name is not None:
            self.calender_name = calender_name
        if email is not None:
            self.email = email
        if account_type is not None:
            self.account_type = account_type
        if status is not None:
            self.status = status
        if device_ip is not None:
            self.device_ip = device_ip
        if camera is not None:
            self.camera = camera
        if microphone is not None:
            self.microphone = microphone
        if speaker is not None:
            self.speaker = speaker
        if last_start_time is not None:
            self.last_start_time = last_start_time
        if location is not None:
            self.location = location
        if health is not None:
            self.health = health
        if issues is not None:
            self.issues = issues

    @property
    def id(self):
        """Gets the id of this ZoomRoom.  # noqa: E501

        Zoom room ID.  # noqa: E501

        :return: The id of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ZoomRoom.

        Zoom room ID.  # noqa: E501

        :param id: The id of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def room_name(self):
        """Gets the room_name of this ZoomRoom.  # noqa: E501

        Zoom room name.  # noqa: E501

        :return: The room_name of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._room_name

    @room_name.setter
    def room_name(self, room_name):
        """Sets the room_name of this ZoomRoom.

        Zoom room name.  # noqa: E501

        :param room_name: The room_name of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._room_name = room_name

    @property
    def calender_name(self):
        """Gets the calender_name of this ZoomRoom.  # noqa: E501

        Zoom calendar name.  # noqa: E501

        :return: The calender_name of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._calender_name

    @calender_name.setter
    def calender_name(self, calender_name):
        """Sets the calender_name of this ZoomRoom.

        Zoom calendar name.  # noqa: E501

        :param calender_name: The calender_name of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._calender_name = calender_name

    @property
    def email(self):
        """Gets the email of this ZoomRoom.  # noqa: E501

        Zoom room email.  # noqa: E501

        :return: The email of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ZoomRoom.

        Zoom room email.  # noqa: E501

        :param email: The email of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def account_type(self):
        """Gets the account_type of this ZoomRoom.  # noqa: E501

        Zoom room email type.  # noqa: E501

        :return: The account_type of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type):
        """Sets the account_type of this ZoomRoom.

        Zoom room email type.  # noqa: E501

        :param account_type: The account_type of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._account_type = account_type

    @property
    def status(self):
        """Gets the status of this ZoomRoom.  # noqa: E501

        Zoom room status.  # noqa: E501

        :return: The status of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ZoomRoom.

        Zoom room status.  # noqa: E501

        :param status: The status of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def device_ip(self):
        """Gets the device_ip of this ZoomRoom.  # noqa: E501

        Zoom room device IP.  # noqa: E501

        :return: The device_ip of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._device_ip

    @device_ip.setter
    def device_ip(self, device_ip):
        """Sets the device_ip of this ZoomRoom.

        Zoom room device IP.  # noqa: E501

        :param device_ip: The device_ip of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._device_ip = device_ip

    @property
    def camera(self):
        """Gets the camera of this ZoomRoom.  # noqa: E501

        Zoom room camera.  # noqa: E501

        :return: The camera of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._camera

    @camera.setter
    def camera(self, camera):
        """Sets the camera of this ZoomRoom.

        Zoom room camera.  # noqa: E501

        :param camera: The camera of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._camera = camera

    @property
    def microphone(self):
        """Gets the microphone of this ZoomRoom.  # noqa: E501

        Zoom room microphone.  # noqa: E501

        :return: The microphone of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._microphone

    @microphone.setter
    def microphone(self, microphone):
        """Sets the microphone of this ZoomRoom.

        Zoom room microphone.  # noqa: E501

        :param microphone: The microphone of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._microphone = microphone

    @property
    def speaker(self):
        """Gets the speaker of this ZoomRoom.  # noqa: E501

        Zoom room speaker.  # noqa: E501

        :return: The speaker of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._speaker

    @speaker.setter
    def speaker(self, speaker):
        """Sets the speaker of this ZoomRoom.

        Zoom room speaker.  # noqa: E501

        :param speaker: The speaker of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._speaker = speaker

    @property
    def last_start_time(self):
        """Gets the last_start_time of this ZoomRoom.  # noqa: E501

        Zoom room last start time.  # noqa: E501

        :return: The last_start_time of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._last_start_time

    @last_start_time.setter
    def last_start_time(self, last_start_time):
        """Sets the last_start_time of this ZoomRoom.

        Zoom room last start time.  # noqa: E501

        :param last_start_time: The last_start_time of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._last_start_time = last_start_time

    @property
    def location(self):
        """Gets the location of this ZoomRoom.  # noqa: E501

        Zoom room location.  # noqa: E501

        :return: The location of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this ZoomRoom.

        Zoom room location.  # noqa: E501

        :param location: The location of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._location = location

    @property
    def health(self):
        """Gets the health of this ZoomRoom.  # noqa: E501


        :return: The health of this ZoomRoom.  # noqa: E501
        :rtype: str
        """
        return self._health

    @health.setter
    def health(self, health):
        """Sets the health of this ZoomRoom.


        :param health: The health of this ZoomRoom.  # noqa: E501
        :type: str
        """

        self._health = health

    @property
    def issues(self):
        """Gets the issues of this ZoomRoom.  # noqa: E501

        Zoom Room issues.  # noqa: E501

        :return: The issues of this ZoomRoom.  # noqa: E501
        :rtype: list[str]
        """
        return self._issues

    @issues.setter
    def issues(self, issues):
        """Sets the issues of this ZoomRoom.

        Zoom Room issues.  # noqa: E501

        :param issues: The issues of this ZoomRoom.  # noqa: E501
        :type: list[str]
        """

        self._issues = issues

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ZoomRoom, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ZoomRoom):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
